# Generated by Django 2.2.7 on 2019-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rsvp.AbstractUser')),
            ],
            bases=('rsvp.abstractuser',),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rsvp.AbstractUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.MainUser')),
            ],
            bases=('rsvp.abstractuser',),
        ),
    ]
