# Generated by Django 2.2.7 on 2019-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='first',
        ),
        migrations.AddField(
            model_name='guest',
            name='last',
            field=models.CharField(default='Lastname', max_length=100),
            preserve_default=False,
        ),
    ]
