# Generated by Django 2.2.7 on 2020-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20191205_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(choices=[(True, 'Will Be Attending'), (False, 'Will Not Be Attending')], default=False),
        ),
    ]
