# Generated by Django 2.2.7 on 2019-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20191122_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
