# Generated by Django 2.2.7 on 2020-01-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20200121_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dietary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='main',
            field=models.CharField(choices=[(0, '------'), (1, 'Slow Roast Rump Beef'), (2, 'Wild Mushroom and Goats Cheese Wellington (V)')], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='guest',
            name='starter',
            field=models.CharField(choices=[(0, '------'), (1, 'Kentish Ranger Chicken Terrine'), (2, 'Heritage Beetroot Tart (V)')], default=0, max_length=200),
        ),
    ]
