# Generated by Django 2.2.7 on 2020-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20200121_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='main',
            field=models.CharField(choices=[('a', '------'), ('b', 'Slow Roast Rump Beef'), ('c', 'Wild Mushroom and Goats Cheese Wellington (V)')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='starter',
            field=models.CharField(choices=[('a', '------'), ('b', 'Kentish Ranger Chicken Terrine'), ('c', 'Heritage Beetroot Tart (V)')], default=0, max_length=200),
        ),
    ]
