# Generated by Django 2.2.7 on 2019-11-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
    ]
