# Generated by Django 2.2.7 on 2020-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_auto_20200121_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='main',
            field=models.CharField(choices=[('a', '------'), ('b', 'Slow Roast Rump Beef - RARE'), ('b2', 'Slow Roast Rump Beef - WELL DONE'), ('c', 'Wild Mushroom and Goats Cheese Wellington (V)')], default=0, max_length=200),
        ),
    ]
