# Generated by Django 2.2.7 on 2020-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20200122_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dessert',
            field=models.CharField(choices=[('a', 'Sticky Toffee Pudding'), ('b', 'Chocolate Delice with Cider and Black')], default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='main',
            field=models.CharField(choices=[('a', '------'), ('b', 'Slow Roast Rump Beef - RARE'), ('b2', 'Slow Roast Rump Beef - WELL DONE'), ('c', 'Wild Mushroom and Goats Cheese Wellington (V)')], default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='starter',
            field=models.CharField(choices=[('a', '------'), ('b', 'Kentish Ranger Chicken Terrine'), ('c', 'Heritage Beetroot Tart (V)')], default='a', max_length=200),
        ),
    ]
