# Generated by Django 2.2.7 on 2019-11-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20191122_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
