# Generated by Django 2.2.7 on 2020-01-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_auto_20200123_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dessert',
            field=models.CharField(choices=[('a', '------'), ('b', 'Sticky Toffee Pudding'), ('c', 'Chocolate Delice with Cider and Black')], default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='main',
            field=models.CharField(choices=[('a', '------'), ('b', 'Slow Roast Rump Beef - MEDIUM RARE'), ('b2', 'Slow Roast Rump Beef - WELL DONE'), ('c', 'Wild Mushroom and Goats Cheese Wellington (V)')], default='a', max_length=200),
        ),
    ]
