# Generated by Django 3.0.2 on 2020-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0010_auto_20200126_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='child',
            field=models.BooleanField(default=False),
        ),
    ]
