# Generated by Django 3.0.2 on 2020-02-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0011_guest_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='child_dessert',
            field=models.CharField(choices=[('a', '------'), ('b', 'Selection of ice creams and berries'), ('c', 'Apple crumble and custard')], default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='guest',
            name='child_main',
            field=models.CharField(choices=[('a', '------'), ('c', 'Macaroni and Cheese'), ('b', 'Beefburger and fries'), ('b2', 'Cheeseburger and fries')], default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='guest',
            name='child_starter',
            field=models.CharField(choices=[('a', '------'), ('b', 'Garlic Bread')], default='a', max_length=200),
        ),
    ]
