# Generated by Django 3.0.2 on 2020-02-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0013_auto_20200203_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='guest',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
