# Generated by Django 3.0.2 on 2020-02-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0014_auto_20200203_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['order', 'last']},
        ),
    ]
