# Generated by Django 3.0.2 on 2020-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0015_auto_20200203_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='child_dessert',
            field=models.CharField(choices=[('a', '------'), ('b', 'Selection of ice creams and berries')], default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='child_starter',
            field=models.CharField(choices=[('a', '------'), ('b', 'Garlic Bread'), ('c', 'Strawberry, melon, and pineapple salad')], default='a', max_length=200),
        ),
    ]
